title: Sam (Ieng-Man) Ng # your name (or website title) here
logo: "/images/111.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  PhD (Economics)
  <br>
  Australian National University
  <br>
  Research fields: Monetary Economics and Banking
  <br><br>
  Welcome to my personal website!
  <br><br>
  Email: samiengmanng@gmail.com 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
